spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/shub-saini/k8s-api-devops-deployment
    targetRevision: main

externalSecrets:
  enabled: true
  namespace: external-secrets-system
  version: 1.3.2
