apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: {{ .Values.backend.deployment.replicaCount }}
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.deployment.image.repository }}:{{ .Values.backend.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.backend.deployment.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.deployment.containerPort }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
          
          resources:
            requests:
              memory: "{{ .Values.backend.deployment.resources.requests.memory }}"
              cpu: "{{ .Values.backend.deployment.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.backend.deployment.resources.limits.memory }}"
              cpu: "{{ .Values.backend.deployment.resources.limits.cpu }}"
          
          volumeMounts:
            - name: db-certs
              mountPath: /app/cert
              readOnly: true

          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.backend.deployment.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.deployment.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
        
      volumes:
        - name: db-certs
          secret:
            secretName: app-secrets
            items:
              - key: ca.pem
                path: ca.pem