apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend-tls-certificate
  namespace: default
spec:
  secretName: backend-cert-secret
  issuerRef:
    name: letsencrypt-ci
    kind: ClusterIssuer
  dnsNames:
    - 'backend.vyntix.tech'

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls-certificate
  namespace: argocd
spec:
  secretName: argo-cert-secret
  issuerRef:
    name: letsencrypt-ci
    kind: ClusterIssuer
  dnsNames:
    - 'argo.vyntix.tech'
