apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vyntix-wildcard-cert
  namespace: default
spec:
  secretName: vyntix-cert-secret
  issuerRef:
    name: letsencrypt-ci
    kind: ClusterIssuer
  dnsNames:
    - '*.vyntix.tech'

  privateKey:
    algorithm: RSA
    size: 2048
