apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: default
spec:
  secretName: tls-cert-ca-key-pair
  issuerRef:
    name: letsencrypt-ci
    kind: ClusterIssuer
  dnsNames:
    - backend.vyntix.tech
