apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator-sa
  namespace: external-secrets-system
  annotations:
    iam.gke.io/gcp-service-account: gke-external-secrets-sa@staging-60514.iam.gserviceaccount.com
