spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/shub-saini/k8s-api-devops-deployment
    targetRevision: main

# Which apps to enable
infrastructure:
  enabled: true
  namespace: argocd

applications:
  enabled: true
  namespace: argocd
