name: Continous Deployment

on:
  workflow_run:
    workflows: ["Continuos Integration"]
    types:
      - completed

jobs:
  update-values-in-helm:
    name: Update Kubernetes values.yaml for Backend service
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update Kubernetes deployment file
        env:
          NEW_IMAGE_TAG: sha-${{ github.event.workflow_run.head_sha }}
        run: |
          # Update the values.yaml file directly
          sed -i "s|tag:.*|tag: ${NEW_IMAGE_TAG}|g" kubernetes/services/backend/values.yaml

          # Verify the change
          echo "Updated deployment to use image: ${NEW_IMAGE_TAG}"
          grep "tag:" kubernetes/services/backend/values.yaml

      - name: Commit and push changes
        env:
          NEW_IMAGE_TAG: sha-${{ github.event.workflow_run.head_sha }}
        run: |
          git add kubernetes/services/backend/values.yaml
          git commit -m "Update Kubernetes deployment with new image tag: ${env.NEW_IMAGE_TAG} [skip ci]" || echo "No changes to commit"
          git push
